### ISSUE TITLE
elems in thead and tfoot not centered as elems tbody

### ISSUE THREAD

**Issue by flowHater** [alvaromontoro/almond.css#49]
**Describe the bug**
Column in thead and tfoot are not centered as it is for tbody

**Steps to reproduce**
go to [the demo](https://alvaromontoro.github.io/almond.css/demo/) look for the `table` section.

**Expected behavior**
I think, It should be elegant and centered the same way

**Screenshots**
![image](https://user-images.githubusercontent.com/45258763/156433277-3c3fc2de-d33b-4d16-b01a-1a56fcea0fb7.png)

**Devices**
Desktop:
 - OS: Linux
 - Browser Firefox
 - Version 97.0.1

**Comment by flowHater** [comment]
Same on chromium. It's not firefox specific

**Comment by tuliopxavier** [comment]
Same on MacOS with Brave, Chrome, Firefox and Safari (latest versions).

On Safari, the top and bottom black borders don't appear (image below).

<img width="1139" alt="Screen Shot 2022-03-04 at 00 32 49" src="https://user-images.githubusercontent.com/68478459/156694307-1445875f-dcf4-4cde-a54a-445b563b721d.png">

**Comment by alvaromontoro** [comment]
Thank you for reporting these issues. They should all be fixed in the latest version:

- `thead` has a bottom border
- `tfoot` has a top border
- the header cells are aligned with the cell content

<img width="1119" alt="screenshot of the demo table for almond.css" src="https://user-images.githubusercontent.com/2205212/212250921-8c3c01c9-66b7-49fb-81db-9c0d5eea85ad.png">
